-- Locked RH schema: deny application access until reviewed RLS policies exist.
-- Generated by scripts/build_locked_schema.py from historical migrations.

-- Historical source: 20260331194617_f1b1ce49-7a54-46d4-93c2-fce493543872.sql
CREATE TABLE public.employees (
  id UUID NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY,
  user_id UUID REFERENCES auth.users(id) ON DELETE SET NULL,
  foto TEXT DEFAULT '',
  nome TEXT NOT NULL,
  cpf TEXT NOT NULL,
  rg TEXT DEFAULT '',
  data_nascimento DATE,
  genero TEXT DEFAULT 'Masculino',
  endereco_rua TEXT DEFAULT '',
  endereco_numero TEXT DEFAULT '',
  endereco_bairro TEXT DEFAULT '',
  endereco_cidade TEXT DEFAULT '',
  endereco_estado TEXT DEFAULT '',
  endereco_cep TEXT DEFAULT '',
  telefone TEXT DEFAULT '',
  chave_pix TEXT,
  tipo_chave_pix TEXT,
  email_pessoal TEXT DEFAULT '',
  matricula TEXT NOT NULL,
  cargo TEXT NOT NULL,
  departamento TEXT NOT NULL,
  centro_custo TEXT DEFAULT '',
  data_admissao DATE NOT NULL,
  tipo_contrato TEXT NOT NULL DEFAULT 'CLT',
  salario NUMERIC(12,2) NOT NULL DEFAULT 0,
  carga_horaria INTEGER DEFAULT 40,
  email_corporativo TEXT DEFAULT '',
  gestor_direto TEXT DEFAULT '',
  status TEXT NOT NULL DEFAULT 'Ativo',
  data_desligamento DATE,
  motivo_desligamento TEXT,
  valor_rescisao NUMERIC(12,2),
  data_pagamento_rescisao DATE,
  pagamento_confirmado BOOLEAN DEFAULT false,
  contrato_assinado BOOLEAN DEFAULT false,
  data_fim_experiencia DATE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE public.evaluations (
  id UUID NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY,
  employee_id UUID REFERENCES public.employees(id) ON DELETE CASCADE NOT NULL,
  periodo TEXT NOT NULL,
  data DATE NOT NULL,
  produtividade NUMERIC(3,1) NOT NULL DEFAULT 0,
  comunicacao NUMERIC(3,1) NOT NULL DEFAULT 0,
  trabalho_equipe NUMERIC(3,1) NOT NULL DEFAULT 0,
  proatividade NUMERIC(3,1) NOT NULL DEFAULT 0,
  lideranca NUMERIC(3,1) NOT NULL DEFAULT 0,
  resultados NUMERIC(3,1) NOT NULL DEFAULT 0,
  pontos_fortes TEXT DEFAULT '',
  pontos_melhoria TEXT DEFAULT '',
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE public.employee_history (
  id UUID NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY,
  employee_id UUID REFERENCES public.employees(id) ON DELETE CASCADE NOT NULL,
  tipo TEXT NOT NULL,
  data DATE NOT NULL,
  descricao TEXT NOT NULL,
  responsavel TEXT DEFAULT '',
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE public.employee_documents (
  id UUID NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY,
  employee_id UUID REFERENCES public.employees(id) ON DELETE CASCADE NOT NULL,
  nome TEXT NOT NULL,
  tipo TEXT NOT NULL,
  data_upload DATE NOT NULL DEFAULT CURRENT_DATE,
  tamanho TEXT DEFAULT '',
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE public.net_salary_columns (
  id UUID NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY,
  year INTEGER NOT NULL,
  month INTEGER NOT NULL,
  column_id TEXT NOT NULL,
  name TEXT NOT NULL,
  type TEXT NOT NULL CHECK (type IN ('earning', 'deduction')),
  sort_order INTEGER DEFAULT 0,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  UNIQUE(year, month, column_id)
);

CREATE TABLE public.net_salary_values (
  id UUID NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY,
  employee_id UUID REFERENCES public.employees(id) ON DELETE CASCADE NOT NULL,
  year INTEGER NOT NULL,
  month INTEGER NOT NULL,
  column_id TEXT NOT NULL,
  value NUMERIC(12,2) NOT NULL DEFAULT 0,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  UNIQUE(employee_id, year, month, column_id)
);

CREATE TABLE public.food_voucher_entries (
  id UUID NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY,
  employee_id UUID REFERENCES public.employees(id) ON DELETE CASCADE NOT NULL,
  year INTEGER NOT NULL,
  month INTEGER NOT NULL,
  value NUMERIC(12,2) NOT NULL DEFAULT 0,
  delivery_method TEXT NOT NULL DEFAULT 'Alelo',
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  UNIQUE(employee_id, year, month)
);

CREATE TABLE public.transport_voucher_entries (
  id UUID NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY,
  employee_id UUID REFERENCES public.employees(id) ON DELETE CASCADE NOT NULL,
  year INTEGER NOT NULL,
  month INTEGER NOT NULL,
  payment1_value NUMERIC(12,2) NOT NULL DEFAULT 0,
  payment1_date TEXT DEFAULT '',
  payment2_value NUMERIC(12,2) NOT NULL DEFAULT 0,
  payment2_date TEXT DEFAULT '',
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  UNIQUE(employee_id, year, month)
);

CREATE TABLE public.expense_categories (
  id UUID NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY,
  year INTEGER NOT NULL,
  month INTEGER NOT NULL,
  name TEXT NOT NULL,
  forecast NUMERIC(12,2) NOT NULL DEFAULT 0,
  spent NUMERIC(12,2) NOT NULL DEFAULT 0,
  sort_order INTEGER DEFAULT 0,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE public.audit_log (
  id UUID NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY,
  user_id TEXT NOT NULL,
  user_name TEXT NOT NULL,
  user_role TEXT NOT NULL,
  action TEXT NOT NULL,
  target TEXT NOT NULL,
  target_id TEXT,
  description TEXT NOT NULL,
  field_changed TEXT,
  old_value TEXT,
  new_value TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

ALTER TABLE public.employees ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.evaluations ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.employee_history ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.employee_documents ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.net_salary_columns ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.net_salary_values ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.food_voucher_entries ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.transport_voucher_entries ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.expense_categories ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.audit_log ENABLE ROW LEVEL SECURITY;











CREATE OR REPLACE FUNCTION public.update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = now();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER update_employees_updated_at BEFORE UPDATE ON public.employees FOR EACH ROW EXECUTE FUNCTION public.update_updated_at_column();
CREATE TRIGGER update_expense_categories_updated_at BEFORE UPDATE ON public.expense_categories FOR EACH ROW EXECUTE FUNCTION public.update_updated_at_column();

-- Historical source: 20260331194716_59a9079e-7e4a-4135-88a8-f4817e722153.sql
CREATE OR REPLACE FUNCTION public.update_updated_at_column()
RETURNS TRIGGER
LANGUAGE plpgsql

SET search_path = public
AS $$
BEGIN
  NEW.updated_at = now();
  RETURN NEW;
END;
$$;

-- Historical source: 20260402122211_eabb3d87-ca96-40a0-a23f-b3be3b45322f.sql
CREATE TABLE public.system_users (
  id uuid NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY,
  auth_user_id uuid REFERENCES auth.users(id) ON DELETE SET NULL,
  nome text NOT NULL,
  email text NOT NULL UNIQUE,
  cargo text NOT NULL DEFAULT '',
  departamento text NOT NULL DEFAULT '',
  nivel_acesso text NOT NULL DEFAULT 'Visualizador',
  status text NOT NULL DEFAULT 'Ativo',
  ultimo_acesso timestamp with time zone DEFAULT now(),
  avatar text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now()
);

ALTER TABLE public.system_users ENABLE ROW LEVEL SECURITY;


CREATE TRIGGER update_system_users_updated_at
  BEFORE UPDATE ON public.system_users
  FOR EACH ROW EXECUTE FUNCTION public.update_updated_at_column();

-- Historical source: 20260403193533_5cc41072-96cf-4988-9f9f-f12a40a1e55e.sql
CREATE TABLE public.departments (
  id uuid NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY,
  name text NOT NULL UNIQUE,
  created_at timestamp with time zone NOT NULL DEFAULT now()
);

ALTER TABLE public.departments ENABLE ROW LEVEL SECURITY;


INSERT INTO public.departments (name) VALUES
  ('Tecnologia'), ('Recursos Humanos'), ('Financeiro'), ('Comercial'), ('Marketing'), ('Operações');

CREATE TABLE public.company_settings (
  id uuid NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY,
  company_name text NOT NULL DEFAULT 'GestãoPeople',
  cnpj text NOT NULL DEFAULT '',
  email text NOT NULL DEFAULT '',
  phone text NOT NULL DEFAULT '',
  updated_at timestamp with time zone NOT NULL DEFAULT now()
);

ALTER TABLE public.company_settings ENABLE ROW LEVEL SECURITY;


INSERT INTO public.company_settings (company_name, cnpj, email, phone)
VALUES ('GestãoPeople LTDA', '12.345.678/0001-90', 'contato@gestapeople.com', '(11) 3000-0000');

-- Historical source: 20260406113141_16c31493-8158-49c8-8db2-89fb47ee8697.sql
INSERT INTO storage.buckets (id, name, public)
VALUES ('avatars', 'avatars', false);

-- Historical source: 20260408155639_0357d78b-244e-46e6-b652-68efc27df26d.sql
CREATE TABLE public.department_managers (
  id UUID NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY,
  department_name TEXT NOT NULL UNIQUE,
  employee_id UUID NOT NULL REFERENCES public.employees(id) ON DELETE CASCADE,
  created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
  updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()
);

ALTER TABLE public.department_managers ENABLE ROW LEVEL SECURITY;


CREATE TRIGGER update_department_managers_updated_at
BEFORE UPDATE ON public.department_managers
FOR EACH ROW
EXECUTE FUNCTION public.update_updated_at_column();

-- Historical source: 20260410184516_fce3a7f0-3c2f-4b30-982f-36c8327f21a9.sql
ALTER TABLE public.employees
ADD COLUMN IF NOT EXISTS data_inicio_aviso_previo date DEFAULT NULL,
ADD COLUMN IF NOT EXISTS desconto_alimentacao numeric DEFAULT 0,
ADD COLUMN IF NOT EXISTS desconto_faltas numeric DEFAULT 0,
ADD COLUMN IF NOT EXISTS aviso_previo_ciente boolean DEFAULT false;

-- Historical source: 20260415132914_dca276a5-10ad-4570-bf41-6bed8e741119.sql
CREATE TABLE public.financial_dashboard_data (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  year integer NOT NULL,
  month integer NOT NULL,
  average_price numeric NOT NULL DEFAULT 0,
  daily_production_avg numeric NOT NULL DEFAULT 0,
  total_pieces numeric NOT NULL DEFAULT 0,
  working_days integer NOT NULL DEFAULT 22,
  revenue_goal numeric NOT NULL DEFAULT 0,
  revenue_billed numeric NOT NULL DEFAULT 0,
  working_days_passed integer NOT NULL DEFAULT 0,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE(year, month)
);

ALTER TABLE public.financial_dashboard_data ENABLE ROW LEVEL SECURITY;


CREATE TABLE public.user_section_permissions (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL REFERENCES public.system_users(id) ON DELETE CASCADE,
  section_key text NOT NULL,
  has_access boolean NOT NULL DEFAULT true,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE(user_id, section_key)
);

ALTER TABLE public.user_section_permissions ENABLE ROW LEVEL SECURITY;

-- Historical source: 20260416160937_31fce715-277a-4f7c-a702-c5dd616a4c30.sql
CREATE TABLE public.food_voucher_settings (
  id uuid NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY,
  year integer NOT NULL,
  month integer NOT NULL,
  benefit_day integer NOT NULL DEFAULT 1,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  UNIQUE(year, month)
);

ALTER TABLE public.food_voucher_settings ENABLE ROW LEVEL SECURITY;

-- Historical source: 20260417144136_fbdc1bf5-6120-4beb-b5a4-fb4ee91020fc.sql
CREATE TABLE public.calendar_deliveries (
  id UUID NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY,
  start_date DATE NOT NULL,
  end_date DATE NOT NULL,
  working_days INTEGER NOT NULL,
  color TEXT NOT NULL,
  color_index INTEGER NOT NULL DEFAULT 0,
  created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
  updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()
);

ALTER TABLE public.calendar_deliveries ENABLE ROW LEVEL SECURITY;


CREATE TABLE public.calendar_receipts (
  id UUID NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY,
  delivery_id UUID NOT NULL REFERENCES public.calendar_deliveries(id) ON DELETE CASCADE,
  receipt_date DATE NOT NULL,
  value NUMERIC NOT NULL DEFAULT 0,
  created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
  updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()
);

ALTER TABLE public.calendar_receipts ENABLE ROW LEVEL SECURITY;


CREATE TRIGGER update_calendar_deliveries_updated_at
BEFORE UPDATE ON public.calendar_deliveries
FOR EACH ROW EXECUTE FUNCTION public.update_updated_at_column();

CREATE TRIGGER update_calendar_receipts_updated_at
BEFORE UPDATE ON public.calendar_receipts
FOR EACH ROW EXECUTE FUNCTION public.update_updated_at_column();

CREATE INDEX idx_calendar_deliveries_dates ON public.calendar_deliveries(start_date, end_date);
CREATE INDEX idx_calendar_receipts_date ON public.calendar_receipts(receipt_date);
CREATE INDEX idx_calendar_receipts_delivery ON public.calendar_receipts(delivery_id);

-- Historical source: 20260420111301_027e3ab2-319b-4937-b1ce-d5b420aea21a.sql
CREATE TABLE public.calendar_week_notes (
  id UUID NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY,
  week_key TEXT NOT NULL UNIQUE,
  note TEXT NOT NULL DEFAULT '',
  created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
  updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()
);

ALTER TABLE public.calendar_week_notes ENABLE ROW LEVEL SECURITY;


CREATE TRIGGER update_calendar_week_notes_updated_at
BEFORE UPDATE ON public.calendar_week_notes
FOR EACH ROW
EXECUTE FUNCTION public.update_updated_at_column();

CREATE INDEX idx_calendar_week_notes_week_key ON public.calendar_week_notes(week_key);

-- Historical source: 20260421113210_df26367b-511b-4600-b126-7f984cac09d1.sql
CREATE TABLE public.cashflow_bucket_categories (
  id uuid NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY,
  bucket text NOT NULL,
  category text NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  UNIQUE(category)
);

ALTER TABLE public.cashflow_bucket_categories ENABLE ROW LEVEL SECURITY;


CREATE INDEX idx_cashflow_bucket_categories_bucket ON public.cashflow_bucket_categories(bucket);

-- Historical source: 20260423180443_39406607-433c-4912-9193-f10c349e8e80.sql
CREATE TABLE IF NOT EXISTS public.cashflow_state (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  state_key text NOT NULL UNIQUE DEFAULT 'default',
  file_name text,
  file_path text,
  entries jsonb NOT NULL DEFAULT '[]'::jsonb,
  start_date text,
  end_date text,
  saved_edits jsonb NOT NULL DEFAULT '{}'::jsonb,
  date_edits jsonb NOT NULL DEFAULT '{}'::jsonb,
  change_history jsonb NOT NULL DEFAULT '[]'::jsonb,
  alteracoes jsonb NOT NULL DEFAULT '[]'::jsonb,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

ALTER TABLE public.cashflow_state ENABLE ROW LEVEL SECURITY;


CREATE TRIGGER update_cashflow_state_updated_at
BEFORE UPDATE ON public.cashflow_state
FOR EACH ROW EXECUTE FUNCTION public.update_updated_at_column();

INSERT INTO storage.buckets (id, name, public)
VALUES ('cashflow-files', 'cashflow-files', false)
ON CONFLICT (id) DO NOTHING;

-- Historical source: 20260424112912_44fc8f83-cecc-4ce1-9483-1deb6bdd4b1b.sql
CREATE TABLE IF NOT EXISTS public.overtime_entries (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  year integer NOT NULL,
  month integer NOT NULL,
  colaborador text NOT NULL,
  employee_id uuid REFERENCES public.employees(id) ON DELETE SET NULL,
  matched boolean NOT NULL DEFAULT false,
  horas numeric NOT NULL DEFAULT 0,
  valor numeric NOT NULL DEFAULT 0,
  file_name text,
  file_path text,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS overtime_entries_year_month_idx ON public.overtime_entries (year, month);

ALTER TABLE public.overtime_entries ENABLE ROW LEVEL SECURITY;


CREATE TRIGGER update_overtime_entries_updated_at
BEFORE UPDATE ON public.overtime_entries
FOR EACH ROW EXECUTE FUNCTION public.update_updated_at_column();

INSERT INTO storage.buckets (id, name, public)
VALUES ('overtime-files', 'overtime-files', false)
ON CONFLICT (id) DO NOTHING;

-- Historical source: 20260430160352_155e25d6-7ef8-4066-bd0f-947431dca490.sql
ALTER TABLE public.employees ADD COLUMN IF NOT EXISTS desconto_farmacia numeric DEFAULT 0;

-- Historical source: 20260519115411_db89ad61-68f2-42d3-b764-fe6d4c87e296.sql
ALTER TABLE public.cashflow_state ADD COLUMN IF NOT EXISTS valor_previsto numeric NOT NULL DEFAULT 0;

-- Historical source: 20260520184917_a418fb86-e6c0-442b-b809-b94f24c0b17a.sql
ALTER TABLE public.cashflow_state
ADD COLUMN IF NOT EXISTS alteracoes_anual jsonb NOT NULL DEFAULT '[]'::jsonb,
ADD COLUMN IF NOT EXISTS valor_previsto_anual numeric NOT NULL DEFAULT 0;

-- Historical source: 20260525132524_0ab97f95-c58a-441c-b4a8-0adbd194289e.sql
UPDATE storage.buckets SET public = false WHERE id IN ('cashflow-files','overtime-files');

-- Historical source: 20260723181727_ba8b1f8f-6fa9-4ebe-8f1d-c4a1007f4a4b.sql
ALTER TABLE public.cashflow_state ADD COLUMN IF NOT EXISTS alteracoes_groups jsonb NOT NULL DEFAULT '[]'::jsonb;

-- Historical source: 20260729145648_04375190-9083-4a21-9f66-690744c0c31d.sql
CREATE TABLE public.daily_summary (
  id UUID NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY,
  summary_date DATE NOT NULL UNIQUE,
  dias_uteis_restante TEXT DEFAULT '',
  faturamento_necessario TEXT DEFAULT '',
  despesas JSONB DEFAULT '[]'::jsonb,
  resultado_inicio TEXT DEFAULT '',
  resultado_ontem TEXT DEFAULT '',
  resultado_hoje TEXT DEFAULT '',
  alteracoes JSONB DEFAULT '[]'::jsonb,
  receitas_dia TEXT DEFAULT '',
  despesas_dia TEXT DEFAULT '',
  avisos JSONB DEFAULT '[]'::jsonb,
  anotacoes TEXT DEFAULT '',
  assinaturas JSONB DEFAULT '[]'::jsonb,
  card_order JSONB DEFAULT '[]'::jsonb,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

GRANT ALL ON public.daily_summary TO service_role;
ALTER TABLE public.daily_summary ENABLE ROW LEVEL SECURITY;

CREATE TRIGGER update_daily_summary_updated_at BEFORE UPDATE ON public.daily_summary FOR EACH ROW EXECUTE FUNCTION public.update_updated_at_column();

-- Historical source: 20260803115730_82beffe1-f714-4b90-a280-e7b74db90932.sql
ALTER TABLE public.daily_summary ADD COLUMN IF NOT EXISTS checklist JSONB NOT NULL DEFAULT '[]'::jsonb;

-- Historical source: 20260804121956_910abef2-35b5-4820-85ad-952eb197271f.sql
ALTER TABLE public.daily_summary
  ADD COLUMN IF NOT EXISTS receitas_receber JSONB NOT NULL DEFAULT '[]'::jsonb,
  ADD COLUMN IF NOT EXISTS receitas_esperadas TEXT NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS despesas_programadas TEXT NOT NULL DEFAULT '';

-- Historical source: 20260807115952_52d98e26-1b3b-4a8a-93e8-53202d4c6100.sql
ALTER TABLE public.daily_summary
  ADD COLUMN IF NOT EXISTS resultado_comp_inicio text DEFAULT ''::text,
  ADD COLUMN IF NOT EXISTS resultado_comp_ontem text DEFAULT ''::text,
  ADD COLUMN IF NOT EXISTS resultado_comp_hoje text DEFAULT ''::text,
  ADD COLUMN IF NOT EXISTS receitas_esperadas_comp text DEFAULT ''::text,
  ADD COLUMN IF NOT EXISTS despesas_programadas_comp text DEFAULT ''::text,
  ADD COLUMN IF NOT EXISTS alteracoes_comp jsonb DEFAULT '[]'::jsonb;

-- Historical source: 20260810135950_8671adf3-46e1-4d2d-906c-2eff85fbe121.sql
CREATE TABLE public.dre_category_map (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  category_name text NOT NULL UNIQUE,
  group_name text NOT NULL,
  sort_order integer DEFAULT 0,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

GRANT ALL ON public.dre_category_map TO service_role;
ALTER TABLE public.dre_category_map ENABLE ROW LEVEL SECURITY;


CREATE TRIGGER update_dre_category_map_updated_at
  BEFORE UPDATE ON public.dre_category_map
  FOR EACH ROW EXECUTE FUNCTION public.update_updated_at_column();

CREATE TABLE public.dre_datasets (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  kind text NOT NULL UNIQUE,
  file_name text,
  months jsonb NOT NULL DEFAULT '[]'::jsonb,
  rows_data jsonb NOT NULL DEFAULT '[]'::jsonb,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

GRANT ALL ON public.dre_datasets TO service_role;
ALTER TABLE public.dre_datasets ENABLE ROW LEVEL SECURITY;


CREATE TRIGGER update_dre_datasets_updated_at
  BEFORE UPDATE ON public.dre_datasets
  FOR EACH ROW EXECUTE FUNCTION public.update_updated_at_column();

-- Historical source: 20260811121927_75213ef5-f60c-417b-9ecd-6163952ec604.sql
ALTER TABLE public.daily_summary
  ADD COLUMN IF NOT EXISTS controle_semanal jsonb NOT NULL DEFAULT '[]'::jsonb,
  ADD COLUMN IF NOT EXISTS objetivo_faturamento text,
  ADD COLUMN IF NOT EXISTS saldo_inicial_dia text,
  ADD COLUMN IF NOT EXISTS saldo_final_dia text;

-- Historical source: 20260820130445_86afc9b3-99d8-47de-a310-afe88814c10b.sql
GRANT ALL ON public.daily_summary TO service_role;

ALTER TABLE public.daily_summary
  ADD COLUMN IF NOT EXISTS resultado_acumulado text,
  ADD COLUMN IF NOT EXISTS possiveis_perdas text,
  ADD COLUMN IF NOT EXISTS controle_ausencias jsonb NOT NULL DEFAULT '[]'::jsonb;

-- Historical source: 20260820135853_c0b1b4a9-5845-40ee-a6c6-c9ed62218775.sql
ALTER TABLE public.employees
  ADD COLUMN IF NOT EXISTS atestado_acompanhante boolean DEFAULT false;

-- Historical source: 20260827124351_8f00fb86-c798-4c9d-8aa7-c0a3f0a0cd1d.sql
ALTER TABLE public.cashflow_state
  ADD COLUMN IF NOT EXISTS valor_previsto_comp numeric NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS valor_previsto_anual_comp numeric NOT NULL DEFAULT 0;

-- Historical source: 20260827125544_7ec21bd2-0583-4a5f-802e-14e080f2d7b8.sql
CREATE TABLE public.hr_process_templates (
  id uuid NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY,
  tipo text NOT NULL,
  nome text NOT NULL,
  sort_order integer NOT NULL DEFAULT 0,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

GRANT ALL ON public.hr_process_templates TO service_role;
ALTER TABLE public.hr_process_templates ENABLE ROW LEVEL SECURITY;

CREATE TRIGGER update_hr_process_templates_updated_at BEFORE UPDATE ON public.hr_process_templates FOR EACH ROW EXECUTE FUNCTION public.update_updated_at_column();

CREATE TABLE public.hr_process_cases (
  id uuid NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY,
  tipo text NOT NULL,
  employee_id uuid NOT NULL REFERENCES public.employees(id) ON DELETE CASCADE,
  data_referencia date,
  observacoes text,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

GRANT ALL ON public.hr_process_cases TO service_role;
ALTER TABLE public.hr_process_cases ENABLE ROW LEVEL SECURITY;

CREATE TRIGGER update_hr_process_cases_updated_at BEFORE UPDATE ON public.hr_process_cases FOR EACH ROW EXECUTE FUNCTION public.update_updated_at_column();

CREATE TABLE public.hr_process_case_steps (
  id uuid NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY,
  case_id uuid NOT NULL REFERENCES public.hr_process_cases(id) ON DELETE CASCADE,
  nome text NOT NULL,
  sort_order integer NOT NULL DEFAULT 0,
  concluido boolean NOT NULL DEFAULT false,
  concluido_em timestamptz,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

GRANT ALL ON public.hr_process_case_steps TO service_role;
ALTER TABLE public.hr_process_case_steps ENABLE ROW LEVEL SECURITY;

CREATE TRIGGER update_hr_process_case_steps_updated_at BEFORE UPDATE ON public.hr_process_case_steps FOR EACH ROW EXECUTE FUNCTION public.update_updated_at_column();

INSERT INTO public.hr_process_templates (tipo, nome, sort_order) VALUES
  ('admissao', 'Documentos recebidos', 1),
  ('admissao', 'Contrato assinado', 2),
  ('admissao', 'Exame admissional', 3),
  ('admissao', 'Cadastro no sistema', 4),
  ('demissao', 'Aviso prévio comunicado', 1),
  ('demissao', 'Exame demissional', 2),
  ('demissao', 'Cálculo da rescisão', 3),
  ('demissao', 'Pagamento da rescisão', 4);

-- Historical source: 20260901143330_80fbd165-688c-4486-9541-afb83a765d5f.sql
ALTER TABLE public.employees ADD COLUMN IF NOT EXISTS conta_santander boolean NOT NULL DEFAULT false;

-- Historical source: 20260903182847_66da04ce-d1e3-4013-98a5-5144421d6d64.sql
ALTER TABLE public.transport_voucher_entries
  ADD COLUMN IF NOT EXISTS payment1_ref_start DATE,
  ADD COLUMN IF NOT EXISTS payment1_ref_end DATE,
  ADD COLUMN IF NOT EXISTS payment2_ref_start DATE,
  ADD COLUMN IF NOT EXISTS payment2_ref_end DATE;
