"""Generate an RH schema baseline with no public or authenticated data policies.

The historical Lovable migrations grant broad access to sensitive records. This
baseline is suitable for preparing an empty Supabase project; application access
must be designed and reviewed separately before importing employee data.
"""

from pathlib import Path
import re

ROOT = Path(__file__).resolve().parents[1]
SOURCES = sorted((ROOT / "supabase" / "migrations").glob("*.sql"))
OUTPUT = ROOT / "supabase" / "baseline" / "rh_locked_schema.sql"

assert len(SOURCES) == 31, "Review newly added migrations before generating a baseline"

parts = []
for source in SOURCES:
    sql = "\n".join(
        line for line in source.read_text(encoding="utf-8").splitlines()
        if not line.lstrip().startswith("--")
    )
    # No broad SELECT/INSERT/UPDATE/DELETE rules from the original app.
    sql = re.sub(r"(?ims)^\s*(?:CREATE|DROP) POLICY\b.*?;", "", sql)
    # A public SECURITY DEFINER function would otherwise be callable via the API.
    sql = re.sub(
        r"(?ims)^\s*CREATE OR REPLACE FUNCTION public\.(?:is_admin|system_users_guard)\(\).*?\$\$;",
        "",
        sql,
    )
    sql = re.sub(r"(?ims)^\s*CREATE TRIGGER system_users_guard_trg\b.*?;", "", sql)
    sql = re.sub(r"(?ims)^\s*DROP TRIGGER IF EXISTS system_users_guard_trg\b.*?;", "", sql)
    sql = re.sub(r"(?im)^\s*SECURITY DEFINER\s*$", "", sql)
    # Buckets containing staff photographs, documents and financial files stay private.
    sql = re.sub(
        r"(VALUES\s*\(\s*'(?:avatars|cashflow-files|overtime-files)'\s*,\s*'[^']+'\s*,\s*)true(\s*\))",
        r"\1false\2",
        sql,
        flags=re.IGNORECASE,
    )
    # Explicit grants from the old migrations are unnecessary in the locked baseline.
    sql = re.sub(r"(?im)^\s*GRANT\b[^;]*\bTO\s+(?:authenticated|anon)\s*;", "", sql)
    parts.append(f"-- Historical source: {source.name}\n{sql.strip()}\n")

result = "\n".join(parts)
tables = re.findall(r"\bCREATE TABLE(?: IF NOT EXISTS)?\s+public\.(\w+)", result, re.I)
rls = re.findall(r"\bALTER TABLE\s+public\.(\w+)\s+ENABLE ROW LEVEL SECURITY", result, re.I)
assert len(tables) == 29 and set(tables) == set(rls), "Every public table must enable RLS"
for forbidden in (r"\bCREATE POLICY\b", r"\bSECURITY DEFINER\b", r"\bpublic\s*=\s*true\b"):
    assert not re.search(forbidden, result, re.I), f"Unsafe SQL: {forbidden}"

OUTPUT.parent.mkdir(parents=True, exist_ok=True)
OUTPUT.write_text(
    "-- Locked RH schema: deny application access until reviewed RLS policies exist.\n"
    "-- Generated by scripts/build_locked_schema.py from historical migrations.\n\n" + result,
    encoding="utf-8",
)
print(f"Generated {OUTPUT.relative_to(ROOT)}: {len(tables)} RLS tables, {len(SOURCES)} sources")
