// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';
import { brokeredPreviewStorage } from './previewAuthStorage';

const SUPABASE_URL = "https://jhvwyrfdbfbhyezstxse.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Impodnd5cmZkYmZiaHllenN0eHNlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzQ5ODIxNTYsImV4cCI6MjA5MDU1ODE1Nn0.4qSsCu-F_HqkfuPZYay6Oin9bRDAk5jCQpNKYkPJgog";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: brokeredPreviewStorage(),
    persistSession: true,
    autoRefreshToken: true,
  }
});